{% set name = "data-diff" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a6e24f4dac25371452e311a5451c957082adb0b2fd544caca0338b87e4d598c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - data-diff = data_diff.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - click >=8.1,<9.0
    - dbt-artifacts-parser >=0.2.4,<0.3.0
    - dbt-core >=1.0.0,<2.0.0
    - dsnparse
    - python >=3.7,<4.0
    - rich
    - runtype >=0.2.6,<0.3.0
    - sqeleton >=0.0.5,<0.0.6
    - toml >=0.10.2,<0.11.0

test:
  imports:
    - data_diff
  commands:
    # - pip check
    - data-diff --help
  # requires:
    # - pip

about:
  home: https://github.com/datafold/data-diff
  doc_url: https://data-diff.readthedocs.io/en/latest/
  summary: Command-line tool and Python library to efficiently diff rows across two different databases.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
