{% set name = "data-diff" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a957195ea6a275a4a05f980f3b157d68bb2f8d57051c0667fb55462b92cea09c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - data-diff = data_diff.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.8.0,<4.0.0
  run:
    - python >=3.8.0,<4.0.0
    - pydantic ==1.10.12
    - dsnparse <0.2.0
    - click >=8.1,<9.0
    - rich
    - toml >=0.10.2,<0.11.0
    - dbt-core >=1.0.0,<2.0.0
    - keyring
    - tabulate >=0.9.0,<0.10.0
    - urllib3 <2
    - typing-extensions >=4.0.1
    - attrs >=23.1.0,<24.0.0

    # These are required though not listed in upstream requirements
    - packaging
    - requests

test:
  imports:
    - data_diff
  commands:
    # Skip pip check due to prance version checking being broken
    - pip check
    - data-diff --help
  requires:
    - pip

about:
  home: https://github.com/datafold/data-diff
  doc_url: https://data-diff.readthedocs.io/en/latest/
  summary: Command-line tool and Python library to efficiently diff rows across two different databases.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
