{% set name = "data-diff" %}
{% set version = "0.7.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2c532a76393df93a445474c1110f55c52652bcca7121bfade800961455abab5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - data-diff = data_diff.__main__:main
    - sqeleton = data_diff.sqeleton.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.7,<4.0
  run:
    - click >=8.1,<9.0
    - dbt-artifacts-parser >=0.3.0,<0.4.0
    - dbt-core >=1.0.0,<2.0.0
    - dsnparse
    - keyring
    - python >=3.7,<4.0
    - rich
    - runtype
    - sqeleton ==0.0.8
    - toml >=0.10.2,<0.11.0
    - tabulate >=0.9.0,<1.0.0
    - urllib3 <2

    # These are required though not listed in upstream requirements
    - packaging
    - pydantic
    - requests

test:
  imports:
    - data_diff
  commands:
  # Skip pip check due to prance version checking being broken
#     - pip check
    - data-diff --help
    - sqeleton --help
  requires:
    - pip

about:
  home: https://github.com/datafold/data-diff
  doc_url: https://data-diff.readthedocs.io/en/latest/
  summary: Command-line tool and Python library to efficiently diff rows across two different databases.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
