{% set name = "data-diff" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4a6d34a5017098673d65dd926335fe602d25ec9159976ead207ebb17528768d0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
  entry_points:
    - data-diff = data_diff.__main__:main

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    # Pinned because pydantic deprecated certain regex function upstream still using
    - pydantic ==1.10.12
    - dsnparse <0.2.0
    - click >=8.1
    - rich
    - toml >=0.10.2
    - dbt-core >=1.0.0,<2.0.0
    - keyring
    - tabulate >=0.9.0
    - urllib3 <2
    - typing-extensions >=4.0.1
    - attrs >=23.1.0
    - mashumaro >=2.9,<3.11.0

    # These are required though not listed in upstream requirements
    - packaging
    - requests

    # From mashumaro[msgpack]
    - msgpack-python >=0.5.6

test:
  imports:
    - data_diff
  commands:
    # Skip pip check due to prance version checking being broken
    - pip check
    - data-diff --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/datafold/data-diff
  doc_url: https://data-diff.readthedocs.io/en/latest/
  summary: Command-line tool and Python library to efficiently diff rows across two different databases.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
